server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #docker run --name nacos-standalone -e MODE=standalone -p 8848:8848 -p 9848:9848 -p 9849:9849 -d nacos/nacos-server:latest
    gateway:
      enabled: true
      routes:
        - id: demo
          uri: http://localhost:6060
          predicates:
            - Method=GET


